iverilog -o test mux.v
iverilog -o test barrel_shifter_16bit.v
iverilog -o test ripple_carry_adder_16bit.v
iverilog -o test adjustMantissa.v
iverilog -o test roundUp.v
iverilog -o test setOutput.v
iverilog -o test adjustOutput.v
iverilog -o test adder.v
iverilog -o test combined_adder.v
